### ISSUE TITLE
1 - 调参及类别不均衡处理

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/dectree_QSO#1]
首先要把模型定好（当然这又跟训练集的比例有关），要考虑到类别不均衡问题。
把模型参数定好之后，开始批量训练和测试。

**Comment by dmyang42** [comment]
类别不平衡问题，顾名思义，即数据集中存在某一类样本，其数量远多于或远少于其他类样本，从而导致一些机器学习模型失效的问题。例如逻辑回归即不适合处理类别不平衡问题，例如逻辑回归在欺诈检测问题中，因为绝大多数样本都为正常样本，欺诈样本很少，逻辑回归算法会倾向于把大多数样本判定为正常样本，这样能达到很高的准确率，但是达不到很高的召回率。

       类别不平衡问题在很多场景中存在，例如欺诈检测，风控识别，在这些样本中，黑样本（一般为存在问题的样本）的数量一般远少于白样本（正常样本）。

       上采样(过采样)和下采样(负采样）策略是解决类别不平衡问题的基本方法之一。上采样即增加少数类样本的数量，下采样即减少多数类样本以获取相对平衡的数据集。

       最简单的上采样方法可以直接将少数类样本复制几份后添加到样本集中，最简单的下采样则可以直接只取一定百分比的多数类样本作为训练集。

       SMOTE算法是用的比较多的一种上采样算法，SMOTE算法的原理并不是太复杂，用python从头实现也只有几十行代码，但是python的imblearn包提供了更方便的接口，在需要快速实现代码的时候可直接调用imblearn。

       imblearn类别不平衡包提供了上采样和下采样策略中的多种接口，基本调用方式一致，主要介绍一下对应的SMOTE方法和下采样中的RandomUnderSampler方法。imblearn可使用pip install imblearn直接安装。

--------------------- 
作者：nlpuser 
来源：CSDN 
原文：https://blog.csdn.net/nlpuser/article/details/81265614 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by dmyang42** [comment]
Solved in #9

**Comment by mostbill** [comment]
做了这个之后分类效果提升了吗？

**Comment by dmyang42** [comment]
qso的precision能提高不少
