### ISSUE TITLE
10 - 可以改善数据集的工作

### ISSUE THREAD

**Issue by mostbill** [topologyYDM/dectree_QSO#11]
关于改善数据集的可以做的事情记录在此。

**Comment by mostbill** [comment]
现在的数据集状态：
1. 光谱认证
QSO: 8236
Star: 3883
Galaxy: 439
2. i<19.0的源
QSO: 2011 (i > 19.0: 6225)
non-QSO: 48104

**Comment by mostbill** [comment]
- 2011 N. Palanque-Delabrouille et al.: 光谱认证的QSO数量达到13,328（用了多个Catalog）

**Comment by dmyang42** [comment]
> 现在的数据集状态：
> 
> 1. 光谱认证
>    QSO: 8236
>    Star: 3883
>    Galaxy: 439
> 2. i<19.0的源
>    QSO: 6458
>    non-QSO: 48104

6458？为什么我这里筛选出来只有两千个

**Comment by dmyang42** [comment]
> * 2011 N. Palanque-Delabrouille et al.: 光谱认证的QSO数量达到13,328（用了多个Catalog）

得保证都有光变曲线

**Comment by dmyang42** [comment]
作废
