### ISSUE TITLE
3 - 预测未知分类 & 其中QSO比例估计

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/dectree_QSO#3]
重新对unknown进行预测，然后根据结果估计s82中qso与star的比例（另外是否存在星系？如果存在星系要先去掉星系，可以看看s82变源catalog是怎么得到的，在[Takata](https://arxiv.org/abs/1811.03837)的文章中有描述）。

**Comment by dmyang42** [comment]
因为估计比例的问题，所以加了effort-medium的标签

**Comment by mostbill** [comment]
根据他们的工作，GALAXY是不是也要match一下？你说的这个工作具体在Takata哪一节？

**Comment by dmyang42** [comment]
> 根据他们的工作，GALAXY是不是也要match一下？你说的这个工作具体在Takata哪一节？

1. unresolved source in imaging data, at least one band with photometric error below 0.05 mag

2. processing ﬂags BRIGHT, SATUR, BLENDED, or EDGE are not set, meaning the measurement performed successfully

3. at least 10 observations in the g and r bands

4. the median g band magnitude brighter than 20.5

5. root-mean-square scatter > 0.05 magnitude and χ 2 per degree of freedom larger than three in both g and r bands, which means the object is ’statistically’ variable in brightness (see the discussions in Sesar et al. (2007) for the details)

**Comment by dmyang42** [comment]
对于绝大多数星系，应该都是**resolved source in imaging data**

**Comment by mostbill** [comment]
> > 根据他们的工作，GALAXY是不是也要match一下？你说的这个工作具体在Takata哪一节？
> 
> 1. unresolved source in imaging data, at least one band with photometric error below 0.05 mag
> 2. processing ﬂags BRIGHT, SATUR, BLENDED, or EDGE are not set, meaning the measurement performed successfully
> 3. at least 10 observations in the g and r bands
> 4. the median g band magnitude brighter than 20.5
> 5. root-mean-square scatter > 0.05 magnitude and χ 2 per degree of freedom larger than three in both g and r bands, which means the object is ’statistically’ variable in brightness (see the discussions in Sesar et al. (2007) for the details)

依据这个criteria，我们还可以加入SDSS-III和SDSS-IV，自己做一个catalog，如果有必要的话。

**Comment by dmyang42** [comment]
那样的话light-curve数据太麻烦了，我感觉至少这次工作没必要了。毕竟这样的话就是要做个更新的s82 variable source catalog出来

**Comment by mostbill** [comment]
然后我没太理解为什么只预测是否存在星系(GALAXY)，'STAR'是不是也可以预测？
然后我们目前只match了'STAR'和'QSO'，也要match一下'GALAXY'吧。

**Comment by dmyang42** [comment]
> 然后我没太理解为什么只预测是否存在星系(GALAXY)，'STAR'是不是也可以预测？
> 然后我们目前只match了'STAR'和'QSO'，也要match一下'GALAXY'吧。

我的意思是这个变源catalog里是否存在星系，如果存在，我们可能先要去掉他们。你可以去把这个天区的星系也download下来，然后match下，说不定还是有几个星系。

**Comment by dmyang42** [comment]
[quasar number density 1](https://spacemath.gsfc.nasa.gov/Calculus/6Page107.pdf)
[quasar number density 2](http://adsbit.harvard.edu/cgi-bin/nph-iarticle_query?1981ApJ...245..375S&defaultprint=YES&page_ind=0&filetype=.pdf)

**Comment by dmyang42** [comment]
作废
