### ISSUE TITLE
4 - 总结重要性评估并重新建立feature列表

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/dectree_QSO#4]
总结各模型特征的重要性评估结果，选择重要特征，重新进行训练，比对结果。

**Comment by dmyang42** [comment]
任务比较重，而且也要重新调参。

**Comment by mostbill** [comment]
1. features重要性研究
- 从17个参数里选出"合适"数量的features，作为新的proper set。原则：不要多余的feature，符合未来观测需求。

2. 重新选取feature进行训练：
- 颜色only
- 光变only
- proper set of features (1.)

**Comment by mostbill** [comment]
Scikit-Learn 里面 *_feature_importances*的参考文献： 经典的那篇Breiman, Friedman, "Classification and regression trees", 1984. (CART): "gini importance" or "mean decrease impurity"

via: https://stackoverflow.com/questions/15810339/how-are-feature-importances-in-randomforestclassifier-determined

**Comment by dmyang42** [comment]
重新建立好的feature列表也要跑一遍，可以参考最新topol branch里只用color或variability的feature来跑的部分。应该只需要改`src/data_util.py`中的`get_feature(mode)`及`loat_data(filename,mode)`两个方法（同时添加一个`important_feature(line)`的方法，同在文件里有参考的）。
