### ISSUE TITLE
7 - LSST&Pan-STARRS的模拟及测试

### ISSUE THREAD

**Issue by mostbill** [topologyYDM/dectree_QSO#7]
需要考虑的：
- 解决不同时(non-simultaneous)band光变曲线的问题(e.g. 2016 Nina et al.)
- 模拟观测效果(e.g. 2010 Macleod et al.)

**Comment by dmyang42** [comment]
模拟观测效果是指啥

**Comment by mostbill** [comment]
> 模拟观测效果是指啥

模拟观测效果即指在“观测长度”，“时间采样”和“不确定度”上模拟一项mission的观测(LSST, etc.)(2010 Macleod et al.)。

Macleod et al.给出了一种估计方法：
“To probe the time scales as short as 0.1τ, and assuming a rest-frame time scale of τ = 10 days and a characteristic redshift of 2, the light curves should be sampled every 3 days in the observer’s frame, which is in good agreement with the baseline cadence of LSST.”

然后他所说的baseline cadence可以在LSST的document中找到：
https://www.lsst.org/sites/default/files/docs/137.03_Pinto_Cadence_Design_8x10.pdf

借用这种转换方法，我们可以对其他未来的测光任务进行模拟并试验我们的分类器。

**Comment by dmyang42** [comment]
我还是没看明白，观测长度、时间采样和不确定度不太清楚含义。以及我们具体做的事情分步骤讲大概是啥

**Comment by mostbill** [comment]
> 我还是没看明白，观测长度、时间采样和不确定度不太清楚含义。以及我们具体做的事情分步骤讲大概是啥

2010 Macleod那篇的5.1, 5.2, 5.3分别讲了这三个事情。关于未来观测任务的模拟我觉得很有必要做，我用ads查了提到LSST的高被引文章，几乎都做了模拟。具体步骤我觉得最简单的就是：
- 模拟观测任务的光变曲线
- 采样，用我们的分类器看看效果

**Comment by dmyang42** [comment]
明白了，不过这个应该是很后面再做的事情。

**Comment by mostbill** [comment]
目前知道的可以讨论的future survey： BOSS, Pan-STARRS, LSST, UKIDSS(near-IR), OGLE

**Comment by dmyang42** [comment]
作废
