### ISSUE TITLE
8 - ”如果有空可以做的“

### ISSUE THREAD

**Issue by mostbill** [topologyYDM/dectree_QSO#8]
一些可以充实论文内容的补充性工作记录在此。

**Comment by mostbill** [comment]
- 补充SDSS-III，SDSS-IV的数据，生成up-to-date的Variable Sources Catalog

**Comment by mostbill** [comment]
- 检查数据集是否是光谱完备的：
(2010 Macleod et al.): The S82 data set is spectroscopically complete for i < 19 in the quasar region of (u − g), (g − r), and (r − i) color space(2002 Richards et al.)
理论上引用这句话就可以说明问题，但是王老师说不排除我们的数据集里有一些不在这一颜色空间里的源。如果是这样，我们得检查一下样本的颜色分布。

**Comment by dmyang42** [comment]
可我们现在的数据里有不少i < 19的还是unlabeled?

**Comment by mostbill** [comment]
> 可我们现在的数据里有不少i < 19的还是unlabeled?

2010 Macleod那篇说过i<19的都做过光谱认证了（我上面那句话），引用的是2002 Richards的工作，我会去确认一下。如果是这样，那么只要我们用的是i<19的，那么non-QSO就一定是non-QSO，今天我问了王老师，'spectroscopically complete'确实是这个意思。

**Comment by dmyang42** [comment]
> > 可我们现在的数据里有不少i < 19的还是unlabeled?
> 
> 2010 Macleod那篇说过i<19的都做过光谱认证了（我上面那句话），引用的是2002 Richards的工作，我会去确认一下。如果是这样，那么只要我们用的是i<19的，那么non-QSO就一定是non-QSO，今天我问了王老师，'spectroscopically complete'确实是这个意思。

> Quasars can be reliably identiﬁed by their spectra, and the SDSS provides a spectroscopically complete survey to i < 19 for the quasar region in SDSS color space (Richards et al. 2002) which includes ∼105,000 quasars (Schneider et al. 2010)

这里的意思不是指所有i < 19的源（包括qso，star，galaxy）吧，2002那篇也只是qso的（是我们之前就看过的那篇，光谱和color选qso的）。我觉得我们前几天那样是没问题的。

**Comment by mostbill** [comment]
> > > 可我们现在的数据里有不少i < 19的还是unlabeled?
> > 
> > 
> > 2010 Macleod那篇说过i<19的都做过光谱认证了（我上面那句话），引用的是2002 Richards的工作，我会去确认一下。如果是这样，那么只要我们用的是i<19的，那么non-QSO就一定是non-QSO，今天我问了王老师，'spectroscopically complete'确实是这个意思。
> 
> > Quasars can be reliably identiﬁed by their spectra, and the SDSS provides a spectroscopically complete survey to i < 19 for the quasar region in SDSS color space (Richards et al. 2002) which includes ∼105,000 quasars (Schneider et al. 2010)
> 
> 这里的意思不是指所有i < 19的源（包括qso，star，galaxy）吧，2002那篇也只是qso的（是我们之前就看过的那篇，光谱和color选qso的）。我觉得我们前几天那样是没问题的。

我再去确认下。

**Comment by mostbill** [comment]
- 将Completeness作为magnitude和redshift的函数

> 2002 Richards et al. 4. Diagnostics: How well does the quasar selection algorithm perform?
> As discussed above, this is really the following two questions: What is the selection efficiency? What is the completeness? We need to know both of these quantities as a function of redshift and magnitude (both apparent and absolute).

**Comment by mostbill** [comment]
- 取X-Ray深场巡天的数据来获得QSO数目，再用那一个天区的photometric data跑一下我们估计的QSO数目，进行对比

P.S. :其实如果拿来只是估计分类效果的话有点多此一举，因为已经有光谱认证对比了，足以说明问题。不过如果像我上面说的一样，将红移纳入分类效果的评判变量，就非常有需要做和深场巡天的对比了。这在其他的'Variability Selected QSO'工作中有提到过：[Variability selected high-redshift quasars on SDSS Stripe 82](https://www.aanda.org/articles/aa/abs/2011/06/aa16254-10/aa16254-10.html)

**Comment by mostbill** [comment]
- 关于采用更新的Catalog

> * 取X-Ray深场巡天的数据来获得QSO数目，再用那一个天区的photometric data跑一下我们估计的QSO数目，进行对比
> 
> P.S. :其实如果拿来只是估计分类效果的话有点多此一举，因为已经有光谱认证对比了，足以说明问题。不过如果像我上面说的一样，将红移纳入分类效果的评判变量，就非常有需要做和深场巡天的对比了。这在其他的'Variability Selected QSO'工作中有提到过：[Variability selected high-redshift quasars on SDSS Stripe 82](https://www.aanda.org/articles/aa/abs/2011/06/aa16254-10/aa16254-10.html)

上面那篇工作用的是2010BOSS的数据，也是simultaneous的多波段观测。

**Comment by dmyang42** [comment]
作废
